steps:
  # Build backend image (re-usable for jobs)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','africa-south1-docker.pkg.dev/$PROJECT_ID/vendora-docker/backend:$BUILD_ID','./backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','africa-south1-docker.pkg.dev/$PROJECT_ID/vendora-docker/backend:$BUILD_ID']

  # Create/Update Cloud Run Job for migrations
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run jobs deploy vendora-migrate \
          --region=africa-south1 \
          --image=africa-south1-docker.pkg.dev/$PROJECT_ID/vendora-docker/backend:$BUILD_ID \
          --service-account=vendora-backend-sa@$PROJECT_ID.iam.gserviceaccount.com \
          --set-secrets=DJANGO_SECRET_KEY=vendora-django-secret:latest \
          -- \
          python manage.py migrate --noinput

  # Create/Update Cloud Run Job for collectstatic (optional)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run jobs deploy vendora-collectstatic \
          --region=africa-south1 \
          --image=africa-south1-docker.pkg.dev/$PROJECT_ID/vendora-docker/backend:$BUILD_ID \
          --service-account=vendora-backend-sa@$PROJECT_ID.iam.gserviceaccount.com \
          --set-secrets=DJANGO_SECRET_KEY=vendora-django-secret:latest \
          -- \
          python manage.py collectstatic --noinput
