# Generated by Django 5.0.7 on 2025-10-05 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platformapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('inapp', 'In-App'), ('whatsapp', 'WhatsApp')], default='email', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('include_tags', models.JSONField(blank=True, default=list)),
                ('exclude_tags', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('from_name', models.CharField(blank=True, max_length=120, null=True)),
                ('from_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=60, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=60, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=60, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('throttle_per_min', models.IntegerField(default=0)),
                ('ab_split', models.FloatField(default=0.0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_key', models.CharField(default='A', max_length=8)),
                ('to_user_id', models.UUIDField(blank=True, null=True)),
                ('to_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('opens', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('bounced', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='marketing.campaign')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_sends', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=24)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marketing.campaign')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_events', to='platformapp.tenant')),
                ('send', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='marketing.campaignsend')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('subject', 'Subject'), ('content', 'Content')], default='content', max_length=16)),
                ('key', models.CharField(default='A', max_length=32)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='marketing.campaign')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_variants', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('definition_json', models.JSONField(blank=True, default=dict)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('approx_count', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='platformapp.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.segment'),
        ),
        migrations.AddIndex(
            model_name='campaignsend',
            index=models.Index(fields=['tenant', 'campaign', 'status', 'to_address'], name='marketing_c_tenant__c1c2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignevent',
            index=models.Index(fields=['tenant', 'campaign', 'event', 'created_at'], name='marketing_c_tenant__ed9bca_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignvariant',
            index=models.Index(fields=['tenant', 'campaign', 'key'], name='marketing_c_tenant__510248_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignvariant',
            unique_together={('campaign', 'key')},
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['tenant', 'name'], name='marketing_s_tenant__3fd923_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'status', 'scheduled_at', 'created_at'], name='marketing_c_tenant__060dc6_idx'),
        ),
    ]
