# Generated by Django 5.0.7 on 2025-10-05 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('platformapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='staff', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='appointments.resource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_schedules', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_min', models.PositiveIntegerField(default=30)),
                ('buffer_before_min', models.PositiveIntegerField(default=0)),
                ('buffer_after_min', models.PositiveIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('resources', models.ManyToManyField(blank=True, related_name='services', to='appointments.resource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(default='booked', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by_user_id', models.UUIDField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(default='web', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='crm.customer')),
                ('reschedule_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedules', to='appointments.booking')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='platformapp.tenant')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='appointments.resource')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='appointments.service')),
            ],
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=160, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeoffs', to='appointments.resource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeoffs', to='platformapp.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['tenant', 'type', 'is_active'], name='appointment_tenant__aa9a96_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceschedule',
            index=models.Index(fields=['tenant', 'resource', 'weekday'], name='appointment_tenant__c92be7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourceschedule',
            unique_together={('resource', 'weekday', 'start_time', 'end_time')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant', 'is_active', 'name'], name='appointment_tenant__2c44dd_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'resource', 'start_at', 'end_at'], name='appointment_tenant__99bbc9_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'status', 'start_at'], name='appointment_tenant__ae3ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoff',
            index=models.Index(fields=['tenant', 'resource', 'start_at', 'end_at'], name='appointment_tenant__dcedbc_idx'),
        ),
    ]
