# Generated by Django 5.0.7 on 2025-10-05 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('platformapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(default='1', max_length=40)),
                ('task', models.CharField(choices=[('fraud', 'Fraud Detection'), ('recommendation', 'Recommendation'), ('forecast', 'Forecast'), ('nlp', 'Natural Language Processing')], max_length=32)),
                ('provider', models.CharField(choices=[('local', 'Local/Embedded'), ('http', 'Remote HTTP'), ('sklearn', 'Scikit-Learn (local)'), ('dummy', 'Dummy (rules/random)')], default='dummy', max_length=24)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('params_json', models.JSONField(blank=True, help_text='Hyperparams/config per provider', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='ready', max_length=24)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='platformapp.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AiJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('train', 'Train'), ('infer', 'Infer'), ('batch_infer', 'Batch Infer'), ('recommend', 'Recommend')], max_length=16)),
                ('entity_type', models.CharField(blank=True, max_length=80, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('priority', models.IntegerField(default=5)),
                ('throttle_per_sec', models.IntegerField(default=50)),
                ('attempts', models.IntegerField(default=0)),
                ('input_json', models.JSONField(blank=True, null=True)),
                ('output_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='platformapp.tenant')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='aiapp.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='AiPrediction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.UUIDField()),
                ('label', models.CharField(blank=True, max_length=64, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('explain_json', models.JSONField(blank=True, null=True)),
                ('features_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='aiapp.aimodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AiRecommendation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.CharField(max_length=80)),
                ('algo', models.CharField(default='popular', max_length=32)),
                ('items_json', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='crm.customer')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='aiapp.aimodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='platformapp.tenant')),
            ],
        ),
    ]
