# Generated by Django 5.0.6 on 2025-10-01 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('platformapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=40)),
                ('task', models.CharField(max_length=32)),
                ('params_json', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platformapp.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AiJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=16)),
                ('entity_type', models.CharField(blank=True, max_length=80, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('input_json', models.JSONField(blank=True, null=True)),
                ('output_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformapp.tenant')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiapp.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='AiPrediction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.UUIDField()),
                ('score', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('explain_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiapp.aimodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AiRecommendation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.CharField(max_length=80)),
                ('items_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiapp.aimodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformapp.tenant')),
            ],
        ),
    ]
