# Generated by Django 5.0.7 on 2025-10-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeebenefit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='onboardingtask',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('skipped', 'Skipped')], default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='payrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('finalized', 'Finalized')], default='draft', max_length=16),
        ),
    ]
