# Generated by Django 5.0.7 on 2025-10-05 21:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('platformapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('sent', 'Sent'), ('paid', 'Paid'), ('void', 'Void'), ('overdue', 'Overdue')], default='open', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('billing_name', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='commerce.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='platformapp.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'number'], name='invoicing_i_tenant__658079_idx'), models.Index(fields=['tenant', 'status', 'issued_at'], name='invoicing_i_tenant__1ea4e6_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(default='TG', max_length=2)),
                ('name', models.CharField(max_length=80)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='platformapp.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'country', 'name'], name='invoicing_t_tenant__563f23_idx')],
                'unique_together': {('tenant', 'country', 'name')},
            },
        ),
    ]
