# Generated by Django 5.0.7 on 2025-10-06 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('platformapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewayaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_subscriptions', related_query_name='payment_subscription', to='platformapp.tenant'),
        ),
    ]
