# Generated by Django 5.0.6 on 2025-10-01 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platformapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDispatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('to_user_id', models.UUIDField(blank=True, null=True)),
                ('to_address', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(default='email', max_length=16)),
                ('payload_json', models.JSONField(default=dict)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_dispatches', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=120)),
                ('provider_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='sent', max_length=16)),
                ('meta_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notificationsapp.notificationdispatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_logs', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField()),
                ('channel', models.CharField(default='email', max_length=16)),
                ('is_enabled', models.BooleanField(default=True)),
                ('quiet_hours_json', models.JSONField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_prefs', to='platformapp.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_key', models.CharField(max_length=120)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('channel', models.CharField(default='email', max_length=16)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_templates', to='platformapp.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notificationdispatch',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificationsapp.notificationtemplate'),
        ),
    ]
