# Generated by Django 5.0.7 on 2025-10-05 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('commerce', '0001_initial'),
        ('platformapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('country', models.CharField(blank=True, default='TG', max_length=2)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_centers', to='platformapp.tenant')),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('label_created', 'Label Created'), ('in_transit', 'In Transit'), ('partial', 'Partial'), ('fulfilled', 'Fulfilled'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('tracking', models.CharField(blank=True, max_length=64, null=True)),
                ('carrier', models.CharField(blank=True, max_length=40, null=True)),
                ('service_level', models.CharField(blank=True, max_length=40, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ship_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ship_currency', models.CharField(default='XOF', max_length=3)),
                ('label_url', models.URLField(blank=True, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='commerce.order')),
                ('pickup_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.pickupcenter')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='platformapp.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='commerce.orderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='platformapp.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.variant')),
            ],
        ),
        migrations.AddIndex(
            model_name='pickupcenter',
            index=models.Index(fields=['tenant', 'code'], name='shipments_p_tenant__438bba_idx'),
        ),
        migrations.AddIndex(
            model_name='pickupcenter',
            index=models.Index(fields=['tenant', 'city'], name='shipments_p_tenant__09f793_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tenant', 'order'], name='shipments_s_tenant__783dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tenant', 'status'], name='shipments_s_tenant__b73f01_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tenant', 'tracking'], name='shipments_s_tenant__f417f1_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['tenant', 'shipment'], name='shipments_s_tenant__21733a_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['tenant', 'status'], name='shipments_s_tenant__8f0040_idx'),
        ),
    ]
