# Generated by Django 5.0.7 on 2025-10-05 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platformapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(blank=True, max_length=80, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=24, null=True)),
                ('country', models.CharField(default='TG', max_length=2)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, max_length=120, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('allow_backorder', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('default_language', models.CharField(default='en', max_length=8)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('social_json', models.JSONField(blank=True, default=dict)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('seo_json', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=140)),
                ('type', models.CharField(choices=[('store', 'Store'), ('office', 'Office'), ('pickup', 'Pickup Center'), ('warehouse', 'Warehouse')], default='store', max_length=32)),
                ('code', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hours_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('manager_user_id', models.UUIDField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.address')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='business.business')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='platformapp.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['tenant', 'city', 'country'], name='business_ad_tenant__215e00_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['tenant', 'is_primary'], name='business_ad_tenant__a2d53f_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['tenant', 'is_public', 'is_active', '-created_at'], name='business_bu_tenant__c4c3de_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['slug'], name='business_bu_slug_860a10_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['name'], name='business_bu_name_217b62_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['tenant', 'business', 'is_public', 'is_active'], name='business_st_tenant__806294_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['business', 'slug'], name='business_st_busines_a9ddc0_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['tenant', 'code'], name='business_st_tenant__43365e_idx'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('business', 'slug'), name='uniq_store_slug_per_business'),
        ),
    ]
