# Generated by Django 5.0.7 on 2025-10-05 21:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('platformapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdpProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traits_json', models.JSONField(blank=True, default=dict)),
                ('search', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdp_profiles', to='crm.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdp_profiles', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CoVisitEdge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_a', models.CharField(db_index=True, max_length=120)),
                ('item_b', models.CharField(db_index=True, max_length=120)),
                ('weight', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covis_edges', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=200)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('fingerprints_json', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprints', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('device_id', models.CharField(blank=True, max_length=64, null=True)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=120)),
                ('client_ts', models.DateTimeField(blank=True, null=True)),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analyticsapp.cdpprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(db_index=True, max_length=120)),
                ('popularity', models.FloatField(default=0.0)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_stats', to='platformapp.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ModelMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_key', models.CharField(max_length=120)),
                ('slice_key', models.CharField(max_length=120)),
                ('auc', models.FloatField(blank=True, null=True)),
                ('pr_auc', models.FloatField(blank=True, null=True)),
                ('precision_at_90_recall', models.FloatField(blank=True, null=True)),
                ('recall_at_1pct_fpr', models.FloatField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_metrics', to='platformapp.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_id', models.CharField(max_length=120)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='XOF', max_length=8)),
                ('channel', models.CharField(default='card', max_length=32)),
                ('country', models.CharField(default='TG', max_length=4)),
                ('features_json', models.JSONField(blank=True, default=dict)),
                ('y_label', models.IntegerField(blank=True, null=True)),
                ('label_source', models.CharField(blank=True, max_length=32, null=True)),
                ('rules_alerts', models.JSONField(blank=True, default=list)),
                ('score', models.FloatField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_signals', to='platformapp.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='cdpprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['traits_json'], name='analyticsap_traits__2e9ba1_gin'),
        ),
        migrations.AddIndex(
            model_name='cdpprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='analyticsap_search_6ec127_gin'),
        ),
        migrations.AddIndex(
            model_name='cdpprofile',
            index=models.Index(fields=['tenant', 'created_at'], name='analyticsap_tenant__d61fbd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='covisitedge',
            unique_together={('tenant', 'item_a', 'item_b')},
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['tenant', 'device_id'], name='analyticsap_tenant__947b95_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['tenant', 'user_id'], name='analyticsap_tenant__c5948f_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['tenant', 'last_seen'], name='analyticsap_tenant__2a17ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicefingerprint',
            unique_together={('tenant', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['props'], name='analyticsap_props_0de402_gin'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tenant', 'name', 'ts'], name='analyticsap_tenant__1aabd7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tenant', 'session_id', 'ts'], name='analyticsap_tenant__0f84ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemstat',
            unique_together={('tenant', 'item_id')},
        ),
        migrations.AddIndex(
            model_name='risksignal',
            index=models.Index(fields=['tenant', 'channel'], name='analyticsap_tenant__065b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='risksignal',
            index=models.Index(fields=['tenant', 'y_label'], name='analyticsap_tenant__316835_idx'),
        ),
        migrations.AddIndex(
            model_name='risksignal',
            index=models.Index(fields=['tenant', 'created_at'], name='analyticsap_tenant__f1f7f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='risksignal',
            unique_together={('tenant', 'tx_id')},
        ),
    ]
