# Generated by Django 5.0.7 on 2025-10-06 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsapp', '0001_initial'),
        ('platformapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicefingerprint',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprints', related_query_name='device_fingerprint', to='platformapp.tenant'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', related_query_name='analytics_event', to='platformapp.tenant'),
        ),
    ]
